<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPDE4CMx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPDE4CMx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPDE4CMx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPDE4CMx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPDE4CMx\App_KernelDevDebugContainer([
    'container.build_hash' => 'PDE4CMx',
    'container.build_id' => '471cfba0',
    'container.build_time' => 1721580435,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPDE4CMx');
