<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaR8UTn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaR8UTn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIaR8UTn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIaR8UTn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIaR8UTn\App_KernelDevDebugContainer([
    'container.build_hash' => 'IaR8UTn',
    'container.build_id' => '99d6afa5',
    'container.build_time' => 1721158084,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaR8UTn');
