<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCqIcssX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCqIcssX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCqIcssX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCqIcssX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCqIcssX\App_KernelDevDebugContainer([
    'container.build_hash' => 'CqIcssX',
    'container.build_id' => '1d162447',
    'container.build_time' => 1721312805,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCqIcssX');
